spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#热部署生效
  spring:
    devtools:
      restart:
        enabled: true
  #设置重启目录
        additional-paths: src/main/java
  #设置classpath目录下的WEB-INF文件夹内容修改不重启
        exclude: static/**


server:
  port: 9099
